[global]
target = "~/.local/bin"
upgrade_only = true

["joho/godotenv"]
["dbrgn/tealdeer"]
["jdx/mise"]
asset_filters = ["x64.tar.gz"]
["ogham/dog"]
asset_filters = ["gnu.zip"]
["atuinsh/atuin"]
asset_filters = ["gnu.tar.gz"]
